CREATE TABLE Authors
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(20),
	LastName NVARCHAR(20),
	BirthDate Date 
);

CREATE TABLE BookBinding
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Type] NVARCHAR(20) UNIQUE NOT NULL
)

CREATE TABLE Publishers
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL,
	Email NVARCHAR(MAX) CHECK(Email LIKE '%@%.%'),
	StreetAddress NVARCHAR(50),
	PostalCode NVARCHAR(50),
	City NVARCHAR(50),
	Country NVARCHAR(50)
);

CREATE TABLE Genres
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Languages
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Books
(
	ISBN13 CHAR(13) PRIMARY KEY	CHECK 
	(
		PATINDEX('%[^0-9]%', ISBN13) = 0 
		AND (ISBN13 LIKE '978%' OR ISBN13 LIKE '979%')
	), 
	Title NVARCHAR(50),
	LanguageId INT FOREIGN KEY REFERENCES Languages(Id),
	GenreId INT FOREIGN KEY REFERENCES Genres(Id),
	Price FLOAT NOT NULL CHECK(Price >= 0),
	PublisherId INT FOREIGN KEY REFERENCES Publishers(Id),
	DatePublished DATE,
	BindingId INT FOREIGN KEY REFERENCES BookBinding(Id)
); 

CREATE TABLE AuthorsBooks
(
	ISBN13 CHAR(13) FOREIGN KEY REFERENCES Books(ISBN13),
	AuthorID INT FOREIGN KEY REFERENCES Authors(Id),
	PRIMARY KEY (ISBN13, AuthorID)
);

CREATE TABLE Stores
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	StreetAddress NVARCHAR(50) NOT NULL,
	PostalCode NVARCHAR(50) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	Country NVARCHAR(50) NOT NULL,
	CONSTRAINT UQStoresNameStreetAddress UNIQUE([Name], StreetAddress)
);

CREATE TABLE Inventories
(
	ISBN13 CHAR(13) FOREIGN KEY REFERENCES Books(ISBN13),
	StoreId INT FOREIGN KEY REFERENCES Stores(Id),
	Quantity INT NOT NULL CHECK(Quantity >= 0) DEFAULT(0),
	PRIMARY KEY(ISBN13, StoreId)
);

CREATE TABLE Customers
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	StreetAddress NVARCHAR(50) NOT NULL,
	PostalCode NVARCHAR(50) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	Country NVARCHAR(50) DEFAULT('Sverige') NOT NULL
 );

 CREATE TABLE OrderStatus
 (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Description] NVARCHAR(20) 
 )

 CREATE TABLE Orders
 (
	Id INT IDENTITY(1000000, 1) PRIMARY KEY,
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(Id),
	StoreId INT FOREIGN KEY REFERENCES Stores(Id),
	[Status] INT NOT NULL FOREIGN KEY REFERENCES OrderStatus(Id),
	TotalAmount FLOAT DEFAULT(0), 
	OrderDate DATETIME2 NOT NULL DEFAULT GETDATE()
 );

 CREATE TABLE BooksOrders
 (
	OrderID INT FOREIGN KEY REFERENCES Orders(Id),
	ISBN13 CHAR(13) FOREIGN KEY REFERENCES Books(ISBN13),
	Quantity INT NOT NULL CHECK(Quantity >= 0) DEFAULT(1),
	PRIMARY KEY (ISBN13, OrderId)
 );


